version: '2.0'
jobs:
  build:
    docker:
      - image: circleci/node:6
    working_directory: ~/auth0-logs-to-datadog
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Check code formatting
          command: yarn lint:js
      - run:
          name: Build client and server bundles
          command: yarn build
