defaults: &node
  working_directory: ~/auth0-logs-to-datadog
  docker:
    - image: circleci/node:6

version: 2
jobs:
  build:
    <<: *node
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Check code formatting
          command: yarn lint:js
      - run:
          name: Build client and server bundles
          command: yarn build

  tag:
    <<: *node
    steps:
      - checkout
      - run:
          name: Create and push git tag
          command: yarn run tag

workflows:
  version: 2
  release:
    jobs:
      - build
      - tag:
          context: default
          requires:
            - build
          filters:
            branches:
              only: master
